version: '1.24'

services:
  db:
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3307:3307"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: mysql+pymysql://$MYSQL_USER:$MYSQL_PASSWORD@db/$MYSQL_DATABASE

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  db_data:
